### ISSUE TITLE
Add an option to change the connection speed

### ISSUE THREAD

**Issue by HvB** [HvB/UsbGps4Droid#1]
The GPS device has sometime to be initialized.
Something like the following commands: 
   su root
   stty -F /dev/ttyUSB0 ispeed 4800

However it would require a rooted device with busybox and superuser installed... stty is not available in the standard android shell.
Should not be a pb, if the device is rooted.

**Comment by HvB** [comment]
should be in next versions UsbPS4Droid_apha4 and UsbPS4Cupcake_apha4

see commits 9f0a1c227d88719094de5da9bc78bd9061b310d1 and e4da3405d83c7c23f07936b366e58e940edd947e

**Comment by shadowpanther** [comment]
If you have busybox, you should call "busybox stty -F ..." instead of "stty -F ...", because stty isn't a standalone binary. Can you change that, or better make an option?
